In [14]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

In [15]:
mnist = fetch_openml('mnist_784', version=1, cache=True, parser='auto') #fetching MNIST dataset

# Prepare features and labels
X = mnist.data.values.astype('float32') / 255.0
y = mnist.target.values.astype('int')

# Split 60k train / 10k test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=60000, test_size=10000, random_state=42)
print(f"Data ready: {X_train.shape[0]} train samples, {X_test.shape[0]} test samples.\n")

Data ready: 60000 train samples, 10000 test samples.

In [16]:
T_checkpoints = [0.1, 1, 2, 3, 4, 10, 30]
methods_rows = [
    'Vote', 'Avg. (unnorm)', 'Avg. (norm)', 
    'Last (unnorm)', 'Last (norm)', 
    'Rand. (unnorm)', 'Rand. (norm)', 
    'SupVec', 'Mistake'
]

In [17]:
def train_predict_linear(X_tr, y_bin, X_test, epochs):
    """Runs Binary Linear Perceptron using dynamically resizing numpy arrays"""
    capacity = 100000
    M_x_arr = np.empty((capacity, X_tr.shape[1]), dtype=np.float32)
    M_y_arr = np.empty(capacity, dtype=np.float32)
    mistake_count = 0
    supvec_indices = set()
    C = [0]

    # Fast Training Phase
    v_curr = np.zeros(X_tr.shape[1], dtype=np.float32)
    for epoch in range(epochs):
        for i in range(len(X_tr)):
            x_i = X_tr[i]
            y_i = y_bin[i]

            y_hat = 1 if np.dot(v_curr, x_i) >= 0 else -1

            if y_hat == y_i:
                C[-1] += 1
            else:
                v_curr += y_i * x_i
                if mistake_count >= capacity:
                    capacity *= 2
                    new_M_x = np.empty((capacity, X_tr.shape[1]), dtype=np.float32)
                    new_M_x[:mistake_count] = M_x_arr
                    M_x_arr = new_M_x
                    
                    new_M_y = np.empty(capacity, dtype=np.float32)
                    new_M_y[:mistake_count] = M_y_arr
                    M_y_arr = new_M_y
                
                M_x_arr[mistake_count] = x_i
                M_y_arr[mistake_count] = y_i
                mistake_count += 1
                supvec_indices.add(i)
                C.append(1)

    # Reconstruction & Prediction Phase
    if mistake_count == 0:
        return (np.zeros(len(X_test)),)*6 + (0, set())

    updates = M_x_arr[:mistake_count] * M_y_arr[:mistake_count][:, np.newaxis]
    V_mat = np.vstack([np.zeros(X_tr.shape[1]), np.cumsum(updates, axis=0)])
    C_vec = np.array(C)

    norms = np.linalg.norm(V_mat, axis=1)
    norms[norms == 0] = 1.0 
    V_mat_norm = V_mat / norms[:, np.newaxis]

    dots_u = np.dot(X_test, V_mat.T)
    dots_n = np.dot(X_test, V_mat_norm.T)
    signs = np.where(dots_u >= 0, 1, -1)

    score_vote = np.dot(signs, C_vec)
    score_avg_u = np.dot(dots_u, C_vec)
    score_avg_n = np.dot(dots_n, C_vec)
    score_last_u = dots_u[:, -1]
    score_last_n = dots_n[:, -1]

    prob_weights = C_vec / np.sum(C_vec)
    score_rand = np.dot(signs, prob_weights)

    return (score_vote, score_avg_u, score_avg_n, score_last_u, 
            score_last_n, score_rand, mistake_count, supvec_indices)

In [18]:
def train_predict_kernel(d, X_tr, y_bin, X_test, epochs):
    """Runs Binary Kernel Perceptron using dynamically resizing numpy arrays"""
    capacity = 100000
    M_x_arr = np.empty((capacity, X_tr.shape[1]), dtype=np.float32)
    M_y_arr = np.empty(capacity, dtype=np.float32)
    mistake_count = 0
    supvec_indices = set()
    C = [0]

    # Fast Training Phase
    for epoch in range(epochs):
        for i in range(len(X_tr)):
            x_i = X_tr[i]
            y_i = y_bin[i]

            if mistake_count == 0:
                v_dot_x = 0.0
            else:
                v_dot_x = np.dot(M_y_arr[:mistake_count], (np.dot(M_x_arr[:mistake_count], x_i) + 1.0) ** d)

            y_hat = 1 if v_dot_x >= 0 else -1

            if y_hat == y_i:
                C[-1] += 1
            else:
                if mistake_count >= capacity:
                    capacity *= 2
                    new_M_x = np.empty((capacity, X_tr.shape[1]), dtype=np.float32)
                    new_M_x[:mistake_count] = M_x_arr
                    M_x_arr = new_M_x
                    
                    new_M_y = np.empty(capacity, dtype=np.float32)
                    new_M_y[:mistake_count] = M_y_arr
                    M_y_arr = new_M_y

                M_x_arr[mistake_count] = x_i
                M_y_arr[mistake_count] = y_i
                mistake_count += 1
                supvec_indices.add(i)
                C.append(1)

    # Prediction Phase
    M_x = M_x_arr[:mistake_count]
    M_y = M_y_arr[:mistake_count]
    C_vec = np.array(C)

    if mistake_count == 0:
         return (np.zeros(len(X_test)),)*6 + (0, set())

    batch_size = 1000
    score_vote, score_avg_u, score_avg_n = [], [], []
    score_last_u, score_last_n, score_rand = [], [], []
    prob_weights = C_vec / np.sum(C_vec)

    for b in range(0, len(X_test), batch_size):
        X_batch = X_test[b:b+batch_size]

        K_matrix = (np.dot(X_batch, M_x.T) + 1.0) ** d
        K_weighted = K_matrix * M_y

        H_vals = np.hstack([np.zeros((len(X_batch), 1)), np.cumsum(K_weighted, axis=1)])
        signs = np.where(H_vals >= 0, 1, -1)

        score_vote.extend(np.dot(signs, C_vec))
        score_last_u.extend(H_vals[:, -1])
        score_last_n.extend(H_vals[:, -1])
        score_avg_u.extend(np.dot(H_vals, C_vec)) 
        score_avg_n.extend(np.dot(H_vals, C_vec))
        score_rand.extend(np.dot(signs, prob_weights))

    return (np.array(score_vote), np.array(score_avg_u), np.array(score_avg_n),
            np.array(score_last_u), np.array(score_last_n), np.array(score_rand),
            mistake_count, supvec_indices)

In [19]:
def run_experiment_for_digit(target_digit, X_train, y_train, X_test, y_test, T_checkpoints, methods_rows):
    """Evaluates the perceptron models for a specific digit vs. all others."""
    
    y_train_bin = np.where(y_train == target_digit, 1, -1)
    y_test_bin = np.where(y_test == target_digit, 1, -1)
    
    table1 = pd.DataFrame(index=pd.MultiIndex.from_product([[1, 2, 3], methods_rows], names=['d', 'Method']), columns=T_checkpoints)
    table2 = pd.DataFrame(index=pd.MultiIndex.from_product([[4, 5, 6], methods_rows], names=['d', 'Method']), columns=T_checkpoints)

    for d in [1, 2, 3, 4, 5, 6]:
        print(f"\n[{target_digit} vs Rest] ======= Polynomial Degree d = {d} =======")
        
        for T in T_checkpoints:
            start_time = time.time()
            
            epochs = 1 if T == 0.1 else int(T)
            limit = 6000 if T == 0.1 else 60000
            
            X_tr = X_train[:limit]
            y_tr = y_train_bin[:limit]
            
            if d == 1:
                res = train_predict_linear(X_tr, y_tr, X_test, epochs)
            else:
                res = train_predict_kernel(d, X_tr, y_tr, X_test, epochs)
                
            scores_vote, scores_avg_u, scores_avg_n, scores_last_u, scores_last_n, scores_rand, mistakes_count, supvecs = res
            
            err_vote = (1 - accuracy_score(y_test_bin, np.where(scores_vote >= 0, 1, -1))) * 100
            err_avg_u = (1 - accuracy_score(y_test_bin, np.where(scores_avg_u >= 0, 1, -1))) * 100
            err_avg_n = (1 - accuracy_score(y_test_bin, np.where(scores_avg_n >= 0, 1, -1))) * 100
            err_last_u = (1 - accuracy_score(y_test_bin, np.where(scores_last_u >= 0, 1, -1))) * 100
            err_last_n = (1 - accuracy_score(y_test_bin, np.where(scores_last_n >= 0, 1, -1))) * 100
            err_rand = (1 - accuracy_score(y_test_bin, np.where(scores_rand >= 0, 1, -1))) * 100
            
            target_table = table1 if d <= 3 else table2
            target_table.loc[(d, 'Vote'), T] = round(err_vote, 1)
            target_table.loc[(d, 'Avg. (unnorm)'), T] = round(err_avg_u, 1)
            target_table.loc[(d, 'Avg. (norm)'), T] = round(err_avg_n, 1)
            target_table.loc[(d, 'Last (unnorm)'), T] = round(err_last_u, 1)
            target_table.loc[(d, 'Last (norm)'), T] = round(err_last_n, 1)
            target_table.loc[(d, 'Rand. (unnorm)'), T] = round(err_rand, 1)
            target_table.loc[(d, 'Rand. (norm)'), T] = round(err_rand, 1)
            target_table.loc[(d, 'SupVec'), T] = len(supvecs)
            target_table.loc[(d, 'Mistake'), T] = mistakes_count
            
            print(f"  T={T:<4} | Mistakes: {mistakes_count:<6} | Test Error: {err_vote:.2f}%  ({time.time() - start_time:.1f}s)")
            
    return table1, table2

In [20]:
all_results = {}
pd.set_option('future.no_silent_downcasting', True)

# Loop through all 10 digits
for digit in range(10):
    print(f"\n{'='*60}")
    print(f" STARTING EXPERIMENT FOR DIGIT: {digit}")
    print(f"{'='*60}")
    
    t1, t2 = run_experiment_for_digit(digit, X_train, y_train, X_test, y_test, T_checkpoints, methods_rows)
    all_results[digit] = {'table1': t1, 'table2': t2}
    
    print(f"\n=================== DIGIT {digit}: TABLE 1 (d=1, 2, 3) ===================")
    display(t1.fillna('-'))
    print(f"\n=================== DIGIT {digit}: TABLE 2 (d=4, 5, 6) ===================")
    display(t2.fillna('-'))

============================================================
 STARTING EXPERIMENT FOR DIGIT: 0
============================================================

[0 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 188    | Test Error: 1.24%  (0.1s)
  T=1    | Mistakes: 1119   | Test Error: 0.94%  (0.6s)
  T=2    | Mistakes: 2042   | Test Error: 0.92%  (1.2s)
  T=3    | Mistakes: 2916   | Test Error: 0.91%  (1.8s)
  T=4    | Mistakes: 3740   | Test Error: 0.89%  (2.3s)
  T=10   | Mistakes: 8393   | Test Error: 0.87%  (5.3s)
  T=30   | Mistakes: 22974  | Test Error: 0.85%  (14.8s)

[0 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 132    | Test Error: 0.92%  (0.8s)
  T=1    | Mistakes: 553    | Test Error: 0.32%  (11.4s)
  T=2    | Mistakes: 813    | Test Error: 0.24%  (24.7s)
  T=3    | Mistakes: 992    | Test Error: 0.19%  (35.7s)
  T=4    | Mistakes: 1160   | Test Error: 0.20%  (49.2s)
  T=10   | Mistakes: 1604   | Test Error: 0.19%  (155.3s)
  T=30   | Mistakes: 1843   | Test Error: 0.20%  (550.8s)

[0 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 119    | Test Error: 0.81%  (0.7s)
  T=1    | Mistakes: 477    | Test Error: 0.28%  (10.5s)
  T=2    | Mistakes: 659    | Test Error: 0.18%  (23.3s)
  T=3    | Mistakes: 739    | Test Error: 0.15%  (39.7s)
  T=4    | Mistakes: 803    | Test Error: 0.14%  (57.1s)
  T=10   | Mistakes: 983    | Test Error: 0.17%  (135.0s)
  T=30   | Mistakes: 1036   | Test Error: 0.18%  (465.0s)

[0 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 123    | Test Error: 0.76%  (0.7s)
  T=1    | Mistakes: 475    | Test Error: 0.27%  (10.3s)
  T=2    | Mistakes: 602    | Test Error: 0.23%  (22.6s)
  T=3    | Mistakes: 673    | Test Error: 0.21%  (39.5s)
  T=4    | Mistakes: 735    | Test Error: 0.19%  (56.9s)
  T=10   | Mistakes: 814    | Test Error: 0.17%  (139.3s)
  T=30   | Mistakes: 814    | Test Error: 0.14%  (406.6s)

[0 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 147    | Test Error: 0.83%  (1.0s)
  T=1    | Mistakes: 486    | Test Error: 0.27%  (11.6s)
  T=2    | Mistakes: 609    | Test Error: 0.23%  (23.4s)
  T=3    | Mistakes: 669    | Test Error: 0.20%  (34.9s)
  T=4    | Mistakes: 695    | Test Error: 0.19%  (46.7s)
  T=10   | Mistakes: 722    | Test Error: 0.16%  (123.2s)
  T=30   | Mistakes: 722    | Test Error: 0.17%  (370.0s)

[0 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 162    | Test Error: 0.82%  (1.0s)
  T=1    | Mistakes: 517    | Test Error: 0.37%  (11.3s)
  T=2    | Mistakes: 634    | Test Error: 0.26%  (23.2s)
  T=3    | Mistakes: 687    | Test Error: 0.25%  (35.6s)
  T=4    | Mistakes: 703    | Test Error: 0.27%  (47.7s)
  T=10   | Mistakes: 716    | Test Error: 0.24%  (125.2s)
  T=30   | Mistakes: 716    | Test Error: 0.23%  (417.3s)

=================== DIGIT 0: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0   4.0   10.0   30.0
d Method
1 Vote            1.2   0.9   0.9   0.9   0.9   0.9    0.8
  Avg. (unnorm)   1.2   0.9   0.9   0.9   0.9   0.9    0.8
  Avg. (norm)     1.2   1.0   0.9   0.9   0.9   0.9    0.8
  Last (unnorm)   2.1   1.3   1.5   1.3   1.2   1.1    1.0
  Last (norm)     2.1   1.3   1.5   1.3   1.2   1.1    1.0
  Rand. (unnorm)  1.2   0.9   0.9   0.9   0.9   0.9    0.8
  Rand. (norm)    1.2   0.9   0.9   0.9   0.9   0.9    0.8
  SupVec          188  1119  1432  1625  1764  2225   2725
  Mistake         188  1119  2042  2916  3740  8393  22974
2 Vote            0.9   0.3   0.2   0.2   0.2   0.2    0.2
  Avg. (unnorm)   0.9   0.3   0.2   0.2   0.2   0.2    0.2
  Avg. (norm)     0.9   0.3   0.2   0.2   0.2   0.2    0.2
  Last (unnorm)   1.2   0.8   0.4   0.6   0.4   0.3    0.2
  Last (norm)     1.2   0.8   0.4   0.6   0.4   0.3    0.2
  Rand. (unnorm)  0.9   0.3   0.2   0.2   0.2   0.2    0.2
  Rand. (norm)    0.9   0.3   0.2   0.2   0.2   0.2    0.2
  SupVec          132   553   702   777   846  1000   1059
  Mistake         132   553   813   992  1160  1604   1843
3 Vote            0.8   0.3   0.2   0.1   0.1   0.2    0.2
  Avg. (unnorm)   0.8   0.3   0.2   0.2   0.1   0.2    0.1
  Avg. (norm)     0.8   0.3   0.2   0.2   0.1   0.2    0.1
  Last (unnorm)   1.2   0.4   0.3   0.2   0.3   0.2    0.2
  Last (norm)     1.2   0.4   0.3   0.2   0.3   0.2    0.2
  Rand. (unnorm)  0.8   0.3   0.2   0.1   0.1   0.2    0.2
  Rand. (norm)    0.8   0.3   0.2   0.1   0.1   0.2    0.2
  SupVec          119   477   594   644   683   775    798
  Mistake         119   477   659   739   803   983   1036

=================== DIGIT 0: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0  2.0  3.0  4.0  10.0 30.0
d Method
4 Vote            0.8  0.3  0.2  0.2  0.2  0.2  0.1
  Avg. (unnorm)   0.7  0.2  0.2  0.2  0.2  0.2  0.1
  Avg. (norm)     0.7  0.2  0.2  0.2  0.2  0.2  0.1
  Last (unnorm)   1.3  0.4  0.3  0.2  0.2  0.1  0.1
  Last (norm)     1.3  0.4  0.3  0.2  0.2  0.1  0.1
  Rand. (unnorm)  0.8  0.3  0.2  0.2  0.2  0.2  0.1
  Rand. (norm)    0.8  0.3  0.2  0.2  0.2  0.2  0.1
  SupVec          123  475  566  613  653  700  700
  Mistake         123  475  602  673  735  814  814
5 Vote            0.8  0.3  0.2  0.2  0.2  0.2  0.2
  Avg. (unnorm)   0.9  0.2  0.2  0.2  0.2  0.2  0.1
  Avg. (norm)     0.9  0.2  0.2  0.2  0.2  0.2  0.1
  Last (unnorm)   1.7  0.5  0.2  0.2  0.2  0.2  0.2
  Last (norm)     1.7  0.5  0.2  0.2  0.2  0.2  0.2
  Rand. (unnorm)  0.8  0.3  0.2  0.2  0.2  0.2  0.2
  Rand. (norm)    0.8  0.3  0.2  0.2  0.2  0.2  0.2
  SupVec          147  486  583  629  641  658  658
  Mistake         147  486  609  669  695  722  722
6 Vote            0.8  0.4  0.3  0.2  0.3  0.2  0.2
  Avg. (unnorm)   0.9  0.3  0.3  0.2  0.2  0.2  0.2
  Avg. (norm)     0.9  0.3  0.3  0.2  0.2  0.2  0.2
  Last (unnorm)   2.2  0.5  0.2  0.3  0.3  0.2  0.2
  Last (norm)     2.2  0.5  0.2  0.3  0.3  0.2  0.2
  Rand. (unnorm)  0.8  0.4  0.3  0.2  0.3  0.2  0.2
  Rand. (norm)    0.8  0.4  0.3  0.2  0.3  0.2  0.2
  SupVec          162  517  612  650  658  668  668
  Mistake         162  517  634  687  703  716  716

============================================================
 STARTING EXPERIMENT FOR DIGIT: 1
============================================================

[1 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 147    | Test Error: 1.08%  (0.1s)
  T=1    | Mistakes: 992    | Test Error: 0.85%  (0.6s)
  T=2    | Mistakes: 1773   | Test Error: 0.82%  (1.1s)
  T=3    | Mistakes: 2571   | Test Error: 0.81%  (1.5s)
  T=4    | Mistakes: 3341   | Test Error: 0.79%  (2.0s)
  T=10   | Mistakes: 7639   | Test Error: 0.80%  (4.8s)
  T=30   | Mistakes: 21015  | Test Error: 0.80%  (13.7s)

[1 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 78     | Test Error: 0.72%  (0.6s)
  T=1    | Mistakes: 435    | Test Error: 0.45%  (10.2s)
  T=2    | Mistakes: 684    | Test Error: 0.34%  (23.7s)
  T=3    | Mistakes: 868    | Test Error: 0.34%  (38.9s)
  T=4    | Mistakes: 997    | Test Error: 0.31%  (52.0s)
  T=10   | Mistakes: 1498   | Test Error: 0.28%  (169.0s)
  T=30   | Mistakes: 1937   | Test Error: 0.28%  (575.2s)

[1 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 77     | Test Error: 0.64%  (0.5s)
  T=1    | Mistakes: 391    | Test Error: 0.32%  (9.2s)
  T=2    | Mistakes: 580    | Test Error: 0.23%  (20.5s)
  T=3    | Mistakes: 692    | Test Error: 0.28%  (32.9s)
  T=4    | Mistakes: 749    | Test Error: 0.25%  (52.9s)
  T=10   | Mistakes: 969    | Test Error: 0.26%  (145.5s)
  T=30   | Mistakes: 1032   | Test Error: 0.26%  (472.0s)

[1 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 69     | Test Error: 0.69%  (0.5s)
  T=1    | Mistakes: 390    | Test Error: 0.38%  (9.5s)
  T=2    | Mistakes: 549    | Test Error: 0.30%  (21.2s)
  T=3    | Mistakes: 623    | Test Error: 0.29%  (34.2s)
  T=4    | Mistakes: 658    | Test Error: 0.30%  (52.1s)
  T=10   | Mistakes: 774    | Test Error: 0.29%  (131.1s)
  T=30   | Mistakes: 783    | Test Error: 0.27%  (438.1s)

[1 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 72     | Test Error: 0.52%  (0.5s)
  T=1    | Mistakes: 383    | Test Error: 0.37%  (9.3s)
  T=2    | Mistakes: 505    | Test Error: 0.24%  (20.4s)
  T=3    | Mistakes: 572    | Test Error: 0.23%  (31.9s)
  T=4    | Mistakes: 600    | Test Error: 0.22%  (46.7s)
  T=10   | Mistakes: 669    | Test Error: 0.23%  (135.3s)
  T=30   | Mistakes: 686    | Test Error: 0.25%  (405.1s)

[1 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 80     | Test Error: 0.64%  (0.5s)
  T=1    | Mistakes: 395    | Test Error: 0.29%  (10.4s)
  T=2    | Mistakes: 498    | Test Error: 0.26%  (23.2s)
  T=3    | Mistakes: 540    | Test Error: 0.26%  (34.2s)
  T=4    | Mistakes: 583    | Test Error: 0.21%  (45.2s)
  T=10   | Mistakes: 607    | Test Error: 0.27%  (131.2s)
  T=30   | Mistakes: 607    | Test Error: 0.27%  (389.2s)

=================== DIGIT 1: TABLE 1 (d=1, 2, 3) ===================

                 0.1  1.0   2.0   3.0   4.0   10.0   30.0
d Method
1 Vote            1.1  0.8   0.8   0.8   0.8   0.8    0.8
  Avg. (unnorm)   1.1  0.9   0.8   0.8   0.8   0.8    0.8
  Avg. (norm)     1.1  0.8   0.8   0.8   0.8   0.8    0.8
  Last (unnorm)   1.2  1.0   1.0   0.9   1.3   0.8    0.9
  Last (norm)     1.2  1.0   1.0   0.9   1.3   0.8    0.9
  Rand. (unnorm)  1.1  0.8   0.8   0.8   0.8   0.8    0.8
  Rand. (norm)    1.1  0.8   0.8   0.8   0.8   0.8    0.8
  SupVec          147  992  1270  1460  1598  1974   2432
  Mistake         147  992  1773  2571  3341  7639  21015
2 Vote            0.7  0.4   0.3   0.3   0.3   0.3    0.3
  Avg. (unnorm)   0.7  0.4   0.3   0.3   0.3   0.3    0.3
  Avg. (norm)     0.7  0.4   0.3   0.3   0.3   0.3    0.3
  Last (unnorm)   1.1  0.6   0.5   0.3   0.4   0.4    0.3
  Last (norm)     1.1  0.6   0.5   0.3   0.4   0.4    0.3
  Rand. (unnorm)  0.7  0.4   0.3   0.3   0.3   0.3    0.3
  Rand. (norm)    0.7  0.4   0.3   0.3   0.3   0.3    0.3
  SupVec           78  435   573   648   694   832    912
  Mistake          78  435   684   868   997  1498   1937
3 Vote            0.6  0.3   0.2   0.3   0.2   0.3    0.3
  Avg. (unnorm)   0.6  0.3   0.2   0.3   0.3   0.3    0.3
  Avg. (norm)     0.6  0.3   0.2   0.3   0.3   0.3    0.3
  Last (unnorm)   0.7  0.4   0.5   0.3   0.3   0.3    0.3
  Last (norm)     0.7  0.4   0.5   0.3   0.3   0.3    0.3
  Rand. (unnorm)  0.6  0.3   0.2   0.3   0.2   0.3    0.3
  Rand. (norm)    0.6  0.3   0.2   0.3   0.2   0.3    0.3
  SupVec           77  391   511   558   585   659    673
  Mistake          77  391   580   692   749   969   1032

=================== DIGIT 1: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0  2.0  3.0  4.0  10.0 30.0
d Method
4 Vote            0.7  0.4  0.3  0.3  0.3  0.3  0.3
  Avg. (unnorm)   0.7  0.4  0.3  0.3  0.3  0.3  0.3
  Avg. (norm)     0.7  0.4  0.3  0.3  0.3  0.3  0.3
  Last (unnorm)   0.7  0.4  0.4  0.3  0.3  0.4  0.3
  Last (norm)     0.7  0.4  0.4  0.3  0.3  0.4  0.3
  Rand. (unnorm)  0.7  0.4  0.3  0.3  0.3  0.3  0.3
  Rand. (norm)    0.7  0.4  0.3  0.3  0.3  0.3  0.3
  SupVec           69  390  494  530  550  601  602
  Mistake          69  390  549  623  658  774  783
5 Vote            0.5  0.4  0.2  0.2  0.2  0.2  0.2
  Avg. (unnorm)   0.5  0.3  0.2  0.2  0.2  0.2  0.2
  Avg. (norm)     0.5  0.3  0.2  0.2  0.2  0.2  0.2
  Last (unnorm)   0.5  0.4  0.3  0.3  0.3  0.3  0.2
  Last (norm)     0.5  0.4  0.3  0.3  0.3  0.3  0.2
  Rand. (unnorm)  0.5  0.4  0.2  0.2  0.2  0.2  0.2
  Rand. (norm)    0.5  0.4  0.2  0.2  0.2  0.2  0.2
  SupVec           72  383  474  510  522  552  556
  Mistake          72  383  505  572  600  669  686
6 Vote            0.6  0.3  0.3  0.3  0.2  0.3  0.3
  Avg. (unnorm)   0.6  0.3  0.2  0.2  0.2  0.2  0.2
  Avg. (norm)     0.6  0.3  0.2  0.2  0.2  0.2  0.2
  Last (unnorm)   3.1  0.6  0.3  0.3  0.3  0.3  0.3
  Last (norm)     3.1  0.6  0.3  0.3  0.3  0.3  0.3
  Rand. (unnorm)  0.6  0.3  0.3  0.3  0.2  0.3  0.3
  Rand. (norm)    0.6  0.3  0.3  0.3  0.2  0.3  0.3
  SupVec           80  395  467  492  520  530  530
  Mistake          80  395  498  540  583  607  607

============================================================
 STARTING EXPERIMENT FOR DIGIT: 2
============================================================

[2 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 338    | Test Error: 2.28%  (0.2s)
  T=1    | Mistakes: 2408   | Test Error: 2.05%  (0.9s)
  T=2    | Mistakes: 4605   | Test Error: 2.00%  (1.8s)
  T=3    | Mistakes: 6669   | Test Error: 1.97%  (2.6s)
  T=4    | Mistakes: 8745   | Test Error: 1.94%  (3.4s)
  T=10   | Mistakes: 20975  | Test Error: 1.89%  (8.0s)
  T=30   | Mistakes: 61063  | Test Error: 1.84%  (26.8s)

[2 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 223    | Test Error: 1.55%  (1.5s)
  T=1    | Mistakes: 1021   | Test Error: 0.78%  (14.1s)
  T=2    | Mistakes: 1489   | Test Error: 0.66%  (35.7s)
  T=3    | Mistakes: 1863   | Test Error: 0.64%  (52.6s)
  T=4    | Mistakes: 2124   | Test Error: 0.61%  (63.4s)
  T=10   | Mistakes: 2987   | Test Error: 0.60%  (215.8s)
  T=30   | Mistakes: 3682   | Test Error: 0.55%  (783.5s)

[2 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 184    | Test Error: 1.15%  (0.9s)
  T=1    | Mistakes: 833    | Test Error: 0.67%  (13.4s)
  T=2    | Mistakes: 1124   | Test Error: 0.58%  (30.6s)
  T=3    | Mistakes: 1325   | Test Error: 0.48%  (49.8s)
  T=4    | Mistakes: 1443   | Test Error: 0.44%  (64.6s)
  T=10   | Mistakes: 1681   | Test Error: 0.41%  (214.6s)
  T=30   | Mistakes: 1773   | Test Error: 0.41%  (611.6s)

[2 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 212    | Test Error: 1.40%  (0.9s)
  T=1    | Mistakes: 826    | Test Error: 0.70%  (13.5s)
  T=2    | Mistakes: 1037   | Test Error: 0.52%  (30.5s)
  T=3    | Mistakes: 1125   | Test Error: 0.52%  (48.8s)
  T=4    | Mistakes: 1146   | Test Error: 0.51%  (59.3s)
  T=10   | Mistakes: 1268   | Test Error: 0.43%  (184.9s)
  T=30   | Mistakes: 1277   | Test Error: 0.46%  (541.7s)

[2 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 213    | Test Error: 1.59%  (0.9s)
  T=1    | Mistakes: 802    | Test Error: 0.62%  (11.6s)
  T=2    | Mistakes: 1018   | Test Error: 0.49%  (25.6s)
  T=3    | Mistakes: 1085   | Test Error: 0.44%  (45.5s)
  T=4    | Mistakes: 1122   | Test Error: 0.47%  (67.2s)
  T=10   | Mistakes: 1193   | Test Error: 0.47%  (165.2s)
  T=30   | Mistakes: 1193   | Test Error: 0.45%  (526.5s)

[2 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 219    | Test Error: 1.61%  (1.0s)
  T=1    | Mistakes: 821    | Test Error: 0.79%  (13.7s)
  T=2    | Mistakes: 1046   | Test Error: 0.62%  (31.8s)
  T=3    | Mistakes: 1112   | Test Error: 0.51%  (40.7s)
  T=4    | Mistakes: 1174   | Test Error: 0.54%  (54.7s)
  T=10   | Mistakes: 1270   | Test Error: 0.57%  (172.8s)
  T=30   | Mistakes: 1270   | Test Error: 0.56%  (527.8s)

=================== DIGIT 2: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0   4.0    10.0   30.0
d Method
1 Vote            2.3   2.0   2.0   2.0   1.9    1.9    1.8
  Avg. (unnorm)   2.3   2.0   2.0   2.0   1.9    1.9    1.8
  Avg. (norm)     2.3   2.0   2.0   2.0   1.9    1.9    1.8
  Last (unnorm)   6.2   4.8   3.5   3.4   2.4    3.1    3.1
  Last (norm)     6.2   4.8   3.5   3.4   2.4    3.1    3.1
  Rand. (unnorm)  2.3   2.0   2.0   2.0   1.9    1.9    1.8
  Rand. (norm)    2.3   2.0   2.0   2.0   1.9    1.9    1.8
  SupVec          338  2408  3198  3656  4005   5053   6393
  Mistake         338  2408  4605  6669  8745  20975  61063
2 Vote            1.5   0.8   0.7   0.6   0.6    0.6    0.5
  Avg. (unnorm)   1.4   0.8   0.6   0.6   0.6    0.6    0.6
  Avg. (norm)     1.4   0.8   0.6   0.6   0.6    0.6    0.6
  Last (unnorm)   2.0   1.2   1.9   0.8   0.7    0.6    0.6
  Last (norm)     2.0   1.2   1.9   0.8   0.7    0.6    0.6
  Rand. (unnorm)  1.5   0.8   0.7   0.6   0.6    0.6    0.5
  Rand. (norm)    1.5   0.8   0.7   0.6   0.6    0.6    0.5
  SupVec          223  1021  1274  1447  1545   1804   1971
  Mistake         223  1021  1489  1863  2124   2987   3682
3 Vote            1.1   0.7   0.6   0.5   0.4    0.4    0.4
  Avg. (unnorm)   1.1   0.7   0.6   0.5   0.5    0.4    0.4
  Avg. (norm)     1.1   0.7   0.6   0.5   0.5    0.4    0.4
  Last (unnorm)   1.8   1.1   0.7   0.7   0.5    0.5    0.4
  Last (norm)     1.8   1.1   0.7   0.7   0.5    0.5    0.4
  Rand. (unnorm)  1.1   0.7   0.6   0.5   0.4    0.4    0.4
  Rand. (norm)    1.1   0.7   0.6   0.5   0.4    0.4    0.4
  SupVec          184   833  1034  1145  1203   1322   1366
  Mistake         184   833  1124  1325  1443   1681   1773

=================== DIGIT 2: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            1.4  0.7   0.5   0.5   0.5   0.4   0.5
  Avg. (unnorm)   1.3  0.6   0.5   0.5   0.5   0.4   0.5
  Avg. (norm)     1.3  0.6   0.5   0.5   0.5   0.4   0.5
  Last (unnorm)   1.9  0.9   0.6   0.5   0.5   0.5   0.5
  Last (norm)     1.9  0.9   0.6   0.5   0.5   0.5   0.5
  Rand. (unnorm)  1.4  0.7   0.5   0.5   0.5   0.4   0.5
  Rand. (norm)    1.4  0.7   0.5   0.5   0.5   0.4   0.5
  SupVec          212  826   971  1024  1038  1117  1124
  Mistake         212  826  1037  1125  1146  1268  1277
5 Vote            1.6  0.6   0.5   0.4   0.5   0.5   0.4
  Avg. (unnorm)   1.4  0.6   0.5   0.4   0.4   0.4   0.4
  Avg. (norm)     1.4  0.6   0.5   0.4   0.4   0.4   0.4
  Last (unnorm)   1.6  0.6   0.6   0.5   0.4   0.4   0.4
  Last (norm)     1.6  0.6   0.6   0.5   0.4   0.4   0.4
  Rand. (unnorm)  1.6  0.6   0.5   0.4   0.5   0.5   0.4
  Rand. (norm)    1.6  0.6   0.5   0.4   0.5   0.5   0.4
  SupVec          213  802   971  1016  1042  1095  1095
  Mistake         213  802  1018  1085  1122  1193  1193
6 Vote            1.6  0.8   0.6   0.5   0.5   0.6   0.6
  Avg. (unnorm)   1.6  0.7   0.6   0.5   0.5   0.5   0.6
  Avg. (norm)     1.6  0.7   0.6   0.5   0.5   0.5   0.6
  Last (unnorm)   2.3  0.8   0.7   0.5   0.9   0.6   0.6
  Last (norm)     2.3  0.8   0.7   0.5   0.9   0.6   0.6
  Rand. (unnorm)  1.6  0.8   0.6   0.5   0.5   0.6   0.6
  Rand. (norm)    1.6  0.8   0.6   0.5   0.5   0.6   0.6
  SupVec          219  821   997  1035  1078  1123  1123
  Mistake         219  821  1046  1112  1174  1270  1270

============================================================
 STARTING EXPERIMENT FOR DIGIT: 3
============================================================

[3 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 389    | Test Error: 3.18%  (0.2s)
  T=1    | Mistakes: 2905   | Test Error: 2.79%  (1.1s)
  T=2    | Mistakes: 5551   | Test Error: 2.75%  (2.0s)
  T=3    | Mistakes: 8208   | Test Error: 2.72%  (3.0s)
  T=4    | Mistakes: 10792  | Test Error: 2.74%  (3.9s)
  T=10   | Mistakes: 26235  | Test Error: 2.79%  (9.5s)
  T=30   | Mistakes: 76913  | Test Error: 2.80%  (33.2s)

[3 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 272    | Test Error: 1.90%  (1.7s)
  T=1    | Mistakes: 1265   | Test Error: 0.85%  (15.3s)
  T=2    | Mistakes: 1924   | Test Error: 0.70%  (41.3s)
  T=3    | Mistakes: 2368   | Test Error: 0.64%  (65.6s)
  T=4    | Mistakes: 2744   | Test Error: 0.62%  (71.9s)
  T=10   | Mistakes: 4063   | Test Error: 0.59%  (243.3s)
  T=30   | Mistakes: 5251   | Test Error: 0.57%  (922.8s)

[3 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 252    | Test Error: 1.64%  (0.9s)
  T=1    | Mistakes: 1045   | Test Error: 0.71%  (13.1s)
  T=2    | Mistakes: 1412   | Test Error: 0.63%  (29.8s)
  T=3    | Mistakes: 1665   | Test Error: 0.55%  (55.6s)
  T=4    | Mistakes: 1814   | Test Error: 0.51%  (88.7s)
  T=10   | Mistakes: 2245   | Test Error: 0.49%  (198.5s)
  T=30   | Mistakes: 2402   | Test Error: 0.52%  (710.1s)

[3 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 257    | Test Error: 1.70%  (1.0s)
  T=1    | Mistakes: 997    | Test Error: 0.77%  (14.8s)
  T=2    | Mistakes: 1256   | Test Error: 0.54%  (34.7s)
  T=3    | Mistakes: 1415   | Test Error: 0.50%  (44.5s)
  T=4    | Mistakes: 1520   | Test Error: 0.52%  (60.8s)
  T=10   | Mistakes: 1762   | Test Error: 0.46%  (195.1s)
  T=30   | Mistakes: 1786   | Test Error: 0.50%  (647.2s)

[3 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 234    | Test Error: 1.80%  (1.0s)
  T=1    | Mistakes: 967    | Test Error: 0.83%  (14.5s)
  T=2    | Mistakes: 1243   | Test Error: 0.62%  (27.1s)
  T=3    | Mistakes: 1351   | Test Error: 0.60%  (42.7s)
  T=4    | Mistakes: 1399   | Test Error: 0.56%  (60.6s)
  T=10   | Mistakes: 1560   | Test Error: 0.52%  (191.2s)
  T=30   | Mistakes: 1560   | Test Error: 0.58%  (622.7s)

[3 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 244    | Test Error: 1.67%  (0.9s)
  T=1    | Mistakes: 1011   | Test Error: 0.68%  (14.8s)
  T=2    | Mistakes: 1297   | Test Error: 0.56%  (27.5s)
  T=3    | Mistakes: 1390   | Test Error: 0.53%  (44.6s)
  T=4    | Mistakes: 1436   | Test Error: 0.52%  (64.8s)
  T=10   | Mistakes: 1478   | Test Error: 0.54%  (193.1s)
  T=30   | Mistakes: 1478   | Test Error: 0.54%  (624.1s)

=================== DIGIT 3: TABLE 1 (d=1, 2, 3) ===================

                  0.1   1.0   2.0   3.0    4.0    10.0   30.0
d Method
1 Vote             3.2   2.8   2.7   2.7    2.7    2.8    2.8
  Avg. (unnorm)    3.1   2.8   2.7   2.7    2.7    2.8    2.8
  Avg. (norm)      3.2   2.8   2.8   2.8    2.7    2.8    2.8
  Last (unnorm)   13.5   4.4   3.7   4.0    3.7    3.7    5.2
  Last (norm)     13.5   4.4   3.7   4.0    3.7    3.7    5.2
  Rand. (unnorm)   3.2   2.8   2.7   2.7    2.7    2.8    2.8
  Rand. (norm)     3.2   2.8   2.7   2.7    2.7    2.8    2.8
  SupVec           389  2905  3800  4355   4721   6007   7527
  Mistake          389  2905  5551  8208  10792  26235  76913
2 Vote             1.9   0.8   0.7   0.6    0.6    0.6    0.6
  Avg. (unnorm)    1.9   0.8   0.7   0.6    0.6    0.6    0.5
  Avg. (norm)      1.9   0.8   0.7   0.6    0.6    0.6    0.5
  Last (unnorm)    2.6   1.2   0.9   1.1    0.8    0.7    0.6
  Last (norm)      2.6   1.2   0.9   1.1    0.8    0.7    0.6
  Rand. (unnorm)   1.9   0.8   0.7   0.6    0.6    0.6    0.6
  Rand. (norm)     1.9   0.8   0.7   0.6    0.6    0.6    0.6
  SupVec           272  1265  1595  1754   1897   2255   2486
  Mistake          272  1265  1924  2368   2744   4063   5251
3 Vote             1.6   0.7   0.6   0.5    0.5    0.5    0.5
  Avg. (unnorm)    1.6   0.7   0.6   0.5    0.5    0.5    0.5
  Avg. (norm)      1.6   0.7   0.6   0.5    0.5    0.5    0.5
  Last (unnorm)    2.8   1.1   0.8   0.7    0.6    0.5    0.5
  Last (norm)      2.8   1.1   0.8   0.7    0.6    0.5    0.5
  Rand. (unnorm)   1.6   0.7   0.6   0.5    0.5    0.5    0.5
  Rand. (norm)     1.6   0.7   0.6   0.5    0.5    0.5    0.5
  SupVec           252  1045  1273  1410   1481   1673   1751
  Mistake          252  1045  1412  1665   1814   2245   2402

=================== DIGIT 3: TABLE 2 (d=4, 5, 6) ===================

                 0.1   1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            1.7   0.8   0.5   0.5   0.5   0.5   0.5
  Avg. (unnorm)   1.7   0.7   0.5   0.5   0.5   0.5   0.5
  Avg. (norm)     1.7   0.7   0.5   0.5   0.5   0.5   0.5
  Last (unnorm)   2.2   0.8   0.6   0.5   0.9   0.5   0.5
  Last (norm)     2.2   0.8   0.6   0.5   0.9   0.5   0.5
  Rand. (unnorm)  1.7   0.8   0.5   0.5   0.5   0.5   0.5
  Rand. (norm)    1.7   0.8   0.5   0.5   0.5   0.5   0.5
  SupVec          257   997  1180  1272  1336  1467  1479
  Mistake         257   997  1256  1415  1520  1762  1786
5 Vote            1.8   0.8   0.6   0.6   0.6   0.5   0.6
  Avg. (unnorm)   1.8   0.8   0.6   0.6   0.6   0.5   0.5
  Avg. (norm)     1.8   0.8   0.6   0.6   0.6   0.5   0.5
  Last (unnorm)   2.3   0.9   0.7   0.6   0.6   0.6   0.6
  Last (norm)     2.3   0.9   0.7   0.6   0.6   0.6   0.6
  Rand. (unnorm)  1.8   0.8   0.6   0.6   0.6   0.5   0.6
  Rand. (norm)    1.8   0.8   0.6   0.6   0.6   0.5   0.6
  SupVec          234   967  1165  1224  1251  1351  1351
  Mistake         234   967  1243  1351  1399  1560  1560
6 Vote            1.7   0.7   0.6   0.5   0.5   0.5   0.5
  Avg. (unnorm)   1.7   0.7   0.6   0.5   0.6   0.6   0.6
  Avg. (norm)     1.7   0.7   0.6   0.5   0.6   0.6   0.6
  Last (unnorm)   2.5   0.8   0.6   0.6   0.5   0.5   0.5
  Last (norm)     2.5   0.8   0.6   0.6   0.5   0.5   0.5
  Rand. (unnorm)  1.7   0.7   0.6   0.5   0.5   0.5   0.5
  Rand. (norm)    1.7   0.7   0.6   0.5   0.5   0.5   0.5
  SupVec          244  1011  1214  1269  1293  1313  1313
  Mistake         244  1011  1297  1390  1436  1478  1478

============================================================
 STARTING EXPERIMENT FOR DIGIT: 4
============================================================

[4 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 291    | Test Error: 2.20%  (0.1s)
  T=1    | Mistakes: 2002   | Test Error: 1.79%  (0.8s)
  T=2    | Mistakes: 3698   | Test Error: 1.79%  (1.6s)
  T=3    | Mistakes: 5353   | Test Error: 1.76%  (2.2s)
  T=4    | Mistakes: 6976   | Test Error: 1.77%  (2.9s)
  T=10   | Mistakes: 16325  | Test Error: 1.83%  (7.2s)
  T=30   | Mistakes: 46113  | Test Error: 1.85%  (20.9s)

[4 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 227    | Test Error: 1.76%  (1.2s)
  T=1    | Mistakes: 948    | Test Error: 0.76%  (12.3s)
  T=2    | Mistakes: 1378   | Test Error: 0.57%  (26.4s)
  T=3    | Mistakes: 1680   | Test Error: 0.51%  (43.3s)
  T=4    | Mistakes: 1876   | Test Error: 0.51%  (75.5s)
  T=10   | Mistakes: 2624   | Test Error: 0.40%  (215.2s)
  T=30   | Mistakes: 2965   | Test Error: 0.47%  (731.6s)

[4 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 189    | Test Error: 1.48%  (0.9s)
  T=1    | Mistakes: 774    | Test Error: 0.54%  (13.4s)
  T=2    | Mistakes: 995    | Test Error: 0.41%  (30.0s)
  T=3    | Mistakes: 1154   | Test Error: 0.37%  (44.8s)
  T=4    | Mistakes: 1293   | Test Error: 0.38%  (58.6s)
  T=10   | Mistakes: 1502   | Test Error: 0.35%  (201.8s)
  T=30   | Mistakes: 1502   | Test Error: 0.32%  (590.3s)

[4 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 195    | Test Error: 1.64%  (0.9s)
  T=1    | Mistakes: 737    | Test Error: 0.45%  (13.1s)
  T=2    | Mistakes: 944    | Test Error: 0.34%  (29.5s)
  T=3    | Mistakes: 1057   | Test Error: 0.34%  (46.8s)
  T=4    | Mistakes: 1109   | Test Error: 0.34%  (57.5s)
  T=10   | Mistakes: 1203   | Test Error: 0.32%  (177.1s)
  T=30   | Mistakes: 1206   | Test Error: 0.37%  (515.1s)

[4 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 198    | Test Error: 1.54%  (0.9s)
  T=1    | Mistakes: 722    | Test Error: 0.45%  (11.3s)
  T=2    | Mistakes: 880    | Test Error: 0.39%  (24.4s)
  T=3    | Mistakes: 976    | Test Error: 0.36%  (38.2s)
  T=4    | Mistakes: 1042   | Test Error: 0.32%  (61.2s)
  T=10   | Mistakes: 1092   | Test Error: 0.35%  (159.4s)
  T=30   | Mistakes: 1092   | Test Error: 0.33%  (490.2s)

[4 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 199    | Test Error: 1.62%  (0.8s)
  T=1    | Mistakes: 756    | Test Error: 0.54%  (11.8s)
  T=2    | Mistakes: 933    | Test Error: 0.47%  (29.0s)
  T=3    | Mistakes: 1068   | Test Error: 0.41%  (48.2s)
  T=4    | Mistakes: 1120   | Test Error: 0.40%  (63.8s)
  T=10   | Mistakes: 1137   | Test Error: 0.40%  (153.1s)
  T=30   | Mistakes: 1137   | Test Error: 0.40%  (499.7s)

=================== DIGIT 4: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0   4.0    10.0   30.0
d Method
1 Vote            2.2   1.8   1.8   1.8   1.8    1.8    1.8
  Avg. (unnorm)   2.2   1.8   1.8   1.7   1.8    1.8    1.8
  Avg. (norm)     2.2   1.8   1.7   1.7   1.8    1.7    1.8
  Last (unnorm)   3.5   2.1   2.6   2.3   2.4    2.2    2.4
  Last (norm)     3.5   2.1   2.6   2.3   2.4    2.2    2.4
  Rand. (unnorm)  2.2   1.8   1.8   1.8   1.8    1.8    1.8
  Rand. (norm)    2.2   1.8   1.8   1.8   1.8    1.8    1.8
  SupVec          291  2002  2588  2943  3195   3889   4651
  Mistake         291  2002  3698  5353  6976  16325  46113
2 Vote            1.8   0.8   0.6   0.5   0.5    0.4    0.5
  Avg. (unnorm)   1.7   0.7   0.6   0.5   0.5    0.4    0.4
  Avg. (norm)     1.7   0.7   0.6   0.5   0.5    0.4    0.4
  Last (unnorm)   2.0   0.8   0.7   0.4   0.5    0.4    0.5
  Last (norm)     2.0   0.8   0.7   0.4   0.5    0.4    0.5
  Rand. (unnorm)  1.8   0.8   0.6   0.5   0.5    0.4    0.5
  Rand. (norm)    1.8   0.8   0.6   0.5   0.5    0.4    0.5
  SupVec          227   948  1187  1318  1396   1629   1701
  Mistake         227   948  1378  1680  1876   2624   2965
3 Vote            1.5   0.5   0.4   0.4   0.4    0.3    0.3
  Avg. (unnorm)   1.4   0.5   0.4   0.4   0.4    0.3    0.3
  Avg. (norm)     1.4   0.5   0.4   0.4   0.4    0.3    0.3
  Last (unnorm)   1.7   0.8   0.4   0.6   0.4    0.3    0.3
  Last (norm)     1.7   0.8   0.4   0.6   0.4    0.3    0.3
  Rand. (unnorm)  1.5   0.5   0.4   0.4   0.4    0.3    0.3
  Rand. (norm)    1.5   0.5   0.4   0.4   0.4    0.3    0.3
  SupVec          189   774   928  1022  1109   1213   1213
  Mistake         189   774   995  1154  1293   1502   1502

=================== DIGIT 4: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0  2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            1.6  0.4  0.3   0.3   0.3   0.3   0.4
  Avg. (unnorm)   1.5  0.4  0.4   0.3   0.3   0.3   0.3
  Avg. (norm)     1.5  0.4  0.4   0.3   0.3   0.3   0.3
  Last (unnorm)   2.8  0.5  0.4   0.4   0.3   0.4   0.4
  Last (norm)     2.8  0.5  0.4   0.4   0.3   0.4   0.4
  Rand. (unnorm)  1.6  0.4  0.3   0.3   0.3   0.3   0.4
  Rand. (norm)    1.6  0.4  0.3   0.3   0.3   0.3   0.4
  SupVec          195  737  897   980  1009  1061  1063
  Mistake         195  737  944  1057  1109  1203  1206
5 Vote            1.5  0.4  0.4   0.4   0.3   0.3   0.3
  Avg. (unnorm)   1.4  0.5  0.4   0.4   0.3   0.3   0.3
  Avg. (norm)     1.4  0.5  0.4   0.4   0.3   0.3   0.3
  Last (unnorm)   2.2  0.4  0.5   0.3   0.3   0.3   0.3
  Last (norm)     2.2  0.4  0.5   0.3   0.3   0.3   0.3
  Rand. (unnorm)  1.5  0.4  0.4   0.4   0.3   0.3   0.3
  Rand. (norm)    1.5  0.4  0.4   0.4   0.3   0.3   0.3
  SupVec          198  722  854   928   978  1004  1004
  Mistake         198  722  880   976  1042  1092  1092
6 Vote            1.6  0.5  0.5   0.4   0.4   0.4   0.4
  Avg. (unnorm)   1.4  0.5  0.4   0.4   0.4   0.4   0.4
  Avg. (norm)     1.4  0.5  0.4   0.4   0.4   0.4   0.4
  Last (unnorm)   2.3  0.6  0.5   0.5   0.4   0.4   0.4
  Last (norm)     2.3  0.6  0.5   0.5   0.4   0.4   0.4
  Rand. (unnorm)  1.6  0.5  0.5   0.4   0.4   0.4   0.4
  Rand. (norm)    1.6  0.5  0.5   0.4   0.4   0.4   0.4
  SupVec          199  756  905  1001  1034  1041  1041
  Mistake         199  756  933  1068  1120  1137  1137

============================================================
 STARTING EXPERIMENT FOR DIGIT: 5
============================================================

[5 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 419    | Test Error: 3.57%  (0.2s)
  T=1    | Mistakes: 3100   | Test Error: 2.68%  (1.1s)
  T=2    | Mistakes: 5787   | Test Error: 2.64%  (2.1s)
  T=3    | Mistakes: 8410   | Test Error: 2.61%  (3.1s)
  T=4    | Mistakes: 10961  | Test Error: 2.60%  (4.1s)
  T=10   | Mistakes: 25805  | Test Error: 2.56%  (9.6s)
  T=30   | Mistakes: 73864  | Test Error: 2.55%  (29.9s)

[5 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 233    | Test Error: 1.67%  (1.4s)
  T=1    | Mistakes: 1098   | Test Error: 0.70%  (13.0s)
  T=2    | Mistakes: 1606   | Test Error: 0.61%  (29.5s)
  T=3    | Mistakes: 1957   | Test Error: 0.57%  (48.5s)
  T=4    | Mistakes: 2245   | Test Error: 0.50%  (82.7s)
  T=10   | Mistakes: 3208   | Test Error: 0.48%  (231.6s)
  T=30   | Mistakes: 3980   | Test Error: 0.48%  (839.7s)

[5 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 201    | Test Error: 1.57%  (0.8s)
  T=1    | Mistakes: 898    | Test Error: 0.51%  (11.8s)
  T=2    | Mistakes: 1227   | Test Error: 0.43%  (26.8s)
  T=3    | Mistakes: 1425   | Test Error: 0.41%  (43.9s)
  T=4    | Mistakes: 1568   | Test Error: 0.43%  (73.8s)
  T=10   | Mistakes: 1840   | Test Error: 0.41%  (200.7s)
  T=30   | Mistakes: 1905   | Test Error: 0.44%  (656.3s)

[5 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 202    | Test Error: 1.77%  (0.8s)
  T=1    | Mistakes: 826    | Test Error: 0.57%  (11.4s)
  T=2    | Mistakes: 1077   | Test Error: 0.42%  (28.7s)
  T=3    | Mistakes: 1178   | Test Error: 0.35%  (49.5s)
  T=4    | Mistakes: 1279   | Test Error: 0.36%  (66.9s)
  T=10   | Mistakes: 1436   | Test Error: 0.34%  (192.2s)
  T=30   | Mistakes: 1444   | Test Error: 0.39%  (583.3s)

[5 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 202    | Test Error: 1.57%  (0.8s)
  T=1    | Mistakes: 838    | Test Error: 0.60%  (11.7s)
  T=2    | Mistakes: 1072   | Test Error: 0.45%  (25.9s)
  T=3    | Mistakes: 1207   | Test Error: 0.44%  (47.0s)
  T=4    | Mistakes: 1286   | Test Error: 0.38%  (69.3s)
  T=10   | Mistakes: 1385   | Test Error: 0.46%  (188.6s)
  T=30   | Mistakes: 1385   | Test Error: 0.47%  (575.5s)

[5 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 214    | Test Error: 2.15%  (0.9s)
  T=1    | Mistakes: 871    | Test Error: 0.55%  (11.9s)
  T=2    | Mistakes: 1103   | Test Error: 0.45%  (26.3s)
  T=3    | Mistakes: 1182   | Test Error: 0.39%  (41.3s)
  T=4    | Mistakes: 1224   | Test Error: 0.39%  (67.3s)
  T=10   | Mistakes: 1255   | Test Error: 0.38%  (174.8s)
  T=30   | Mistakes: 1255   | Test Error: 0.38%  (526.5s)

=================== DIGIT 5: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0    4.0    10.0   30.0
d Method
1 Vote            3.6   2.7   2.6   2.6    2.6    2.6    2.5
  Avg. (unnorm)   3.5   2.7   2.6   2.6    2.6    2.6    2.5
  Avg. (norm)     3.9   2.7   2.7   2.6    2.6    2.6    2.6
  Last (unnorm)   4.0   6.9   5.9   6.0    5.5    5.0    6.8
  Last (norm)     4.0   6.9   5.9   6.0    5.5    5.0    6.8
  Rand. (unnorm)  3.6   2.7   2.6   2.6    2.6    2.6    2.5
  Rand. (norm)    3.6   2.7   2.6   2.6    2.6    2.6    2.5
  SupVec          419  3100  4012  4602   5025   6266   7665
  Mistake         419  3100  5787  8410  10961  25805  73864
2 Vote            1.7   0.7   0.6   0.6    0.5    0.5    0.5
  Avg. (unnorm)   1.6   0.7   0.6   0.6    0.5    0.5    0.5
  Avg. (norm)     1.6   0.7   0.6   0.6    0.5    0.5    0.5
  Last (unnorm)   1.9   1.4   0.8   0.6    0.8    0.8    0.5
  Last (norm)     1.9   1.4   0.8   0.6    0.8    0.8    0.5
  Rand. (unnorm)  1.7   0.7   0.6   0.6    0.5    0.5    0.5
  Rand. (norm)    1.7   0.7   0.6   0.6    0.5    0.5    0.5
  SupVec          233  1098  1356  1506   1606   1884   2054
  Mistake         233  1098  1606  1957   2245   3208   3980
3 Vote            1.6   0.5   0.4   0.4    0.4    0.4    0.4
  Avg. (unnorm)   1.5   0.5   0.4   0.4    0.4    0.4    0.4
  Avg. (norm)     1.5   0.5   0.4   0.4    0.4    0.4    0.4
  Last (unnorm)   1.8   0.7   1.1   0.6    0.6    0.5    0.5
  Last (norm)     1.8   0.7   1.1   0.6    0.6    0.5    0.5
  Rand. (unnorm)  1.6   0.5   0.4   0.4    0.4    0.4    0.4
  Rand. (norm)    1.6   0.5   0.4   0.4    0.4    0.4    0.4
  SupVec          201   898  1116  1224   1303   1438   1462
  Mistake         201   898  1227  1425   1568   1840   1905

=================== DIGIT 5: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            1.8  0.6   0.4   0.3   0.4   0.3   0.4
  Avg. (unnorm)   1.6  0.5   0.4   0.3   0.3   0.3   0.4
  Avg. (norm)     1.6  0.5   0.4   0.3   0.3   0.3   0.4
  Last (unnorm)   1.4  1.5   0.5   0.4   0.5   0.3   0.4
  Last (norm)     1.4  1.5   0.5   0.4   0.5   0.3   0.4
  Rand. (unnorm)  1.8  0.6   0.4   0.3   0.4   0.3   0.4
  Rand. (norm)    1.8  0.6   0.4   0.3   0.4   0.3   0.4
  SupVec          202  826  1012  1075  1136  1228  1234
  Mistake         202  826  1077  1178  1279  1436  1444
5 Vote            1.6  0.6   0.4   0.4   0.4   0.5   0.5
  Avg. (unnorm)   1.4  0.6   0.4   0.5   0.4   0.4   0.4
  Avg. (norm)     1.4  0.6   0.4   0.5   0.4   0.4   0.4
  Last (unnorm)   1.5  0.6   0.8   0.5   0.5   0.5   0.5
  Last (norm)     1.5  0.6   0.8   0.5   0.5   0.5   0.5
  Rand. (unnorm)  1.6  0.6   0.4   0.4   0.4   0.5   0.5
  Rand. (norm)    1.6  0.6   0.4   0.4   0.4   0.5   0.5
  SupVec          202  838  1013  1111  1170  1236  1236
  Mistake         202  838  1072  1207  1286  1385  1385
6 Vote            2.1  0.5   0.4   0.4   0.4   0.4   0.4
  Avg. (unnorm)   2.0  0.5   0.4   0.4   0.4   0.4   0.4
  Avg. (norm)     2.0  0.5   0.4   0.4   0.4   0.4   0.4
  Last (unnorm)   1.7  0.8   0.5   0.4   0.5   0.4   0.4
  Last (norm)     1.7  0.8   0.5   0.4   0.5   0.4   0.4
  Rand. (unnorm)  2.1  0.5   0.4   0.4   0.4   0.4   0.4
  Rand. (norm)    2.1  0.5   0.4   0.4   0.4   0.4   0.4
  SupVec          214  871  1050  1101  1124  1142  1142
  Mistake         214  871  1103  1182  1224  1255  1255

============================================================
 STARTING EXPERIMENT FOR DIGIT: 6
============================================================

[6 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 193    | Test Error: 1.81%  (0.1s)
  T=1    | Mistakes: 1537   | Test Error: 1.38%  (0.7s)
  T=2    | Mistakes: 2919   | Test Error: 1.46%  (1.4s)
  T=3    | Mistakes: 4210   | Test Error: 1.43%  (2.0s)
  T=4    | Mistakes: 5500   | Test Error: 1.46%  (2.6s)
  T=10   | Mistakes: 13076  | Test Error: 1.44%  (6.2s)
  T=30   | Mistakes: 37487  | Test Error: 1.38%  (18.1s)

[6 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 124    | Test Error: 1.00%  (0.9s)
  T=1    | Mistakes: 653    | Test Error: 0.44%  (11.7s)
  T=2    | Mistakes: 978    | Test Error: 0.35%  (27.8s)
  T=3    | Mistakes: 1228   | Test Error: 0.30%  (38.6s)
  T=4    | Mistakes: 1404   | Test Error: 0.32%  (52.4s)
  T=10   | Mistakes: 1986   | Test Error: 0.29%  (188.3s)
  T=30   | Mistakes: 2373   | Test Error: 0.30%  (657.0s)

[6 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 113    | Test Error: 0.95%  (0.8s)
  T=1    | Mistakes: 556    | Test Error: 0.42%  (11.6s)
  T=2    | Mistakes: 766    | Test Error: 0.34%  (26.2s)
  T=3    | Mistakes: 864    | Test Error: 0.32%  (35.8s)
  T=4    | Mistakes: 949    | Test Error: 0.29%  (49.6s)
  T=10   | Mistakes: 1127   | Test Error: 0.25%  (161.8s)
  T=30   | Mistakes: 1140   | Test Error: 0.25%  (499.0s)

[6 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 122    | Test Error: 1.09%  (0.8s)
  T=1    | Mistakes: 509    | Test Error: 0.40%  (10.3s)
  T=2    | Mistakes: 682    | Test Error: 0.36%  (22.9s)
  T=3    | Mistakes: 770    | Test Error: 0.33%  (37.2s)
  T=4    | Mistakes: 822    | Test Error: 0.32%  (55.1s)
  T=10   | Mistakes: 951    | Test Error: 0.32%  (146.8s)
  T=30   | Mistakes: 959    | Test Error: 0.28%  (469.0s)

[6 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 118    | Test Error: 1.14%  (0.7s)
  T=1    | Mistakes: 560    | Test Error: 0.32%  (10.2s)
  T=2    | Mistakes: 715    | Test Error: 0.30%  (22.6s)
  T=3    | Mistakes: 757    | Test Error: 0.32%  (35.2s)
  T=4    | Mistakes: 771    | Test Error: 0.31%  (57.9s)
  T=10   | Mistakes: 799    | Test Error: 0.34%  (145.0s)
  T=30   | Mistakes: 799    | Test Error: 0.33%  (440.2s)

[6 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 135    | Test Error: 1.04%  (0.8s)
  T=1    | Mistakes: 552    | Test Error: 0.44%  (10.6s)
  T=2    | Mistakes: 685    | Test Error: 0.33%  (23.4s)
  T=3    | Mistakes: 731    | Test Error: 0.29%  (37.2s)
  T=4    | Mistakes: 734    | Test Error: 0.29%  (57.1s)
  T=10   | Mistakes: 743    | Test Error: 0.31%  (136.9s)
  T=30   | Mistakes: 743    | Test Error: 0.31%  (436.5s)

=================== DIGIT 6: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0   4.0    10.0   30.0
d Method
1 Vote            1.8   1.4   1.5   1.4   1.5    1.4    1.4
  Avg. (unnorm)   1.7   1.4   1.5   1.4   1.5    1.4    1.4
  Avg. (norm)     1.8   1.4   1.5   1.4   1.4    1.4    1.4
  Last (unnorm)   2.0   2.1   3.2   2.8   1.9    4.4    3.2
  Last (norm)     2.0   2.1   3.2   2.8   1.9    4.4    3.2
  Rand. (unnorm)  1.8   1.4   1.5   1.4   1.5    1.4    1.4
  Rand. (norm)    1.8   1.4   1.5   1.4   1.5    1.4    1.4
  SupVec          193  1537  2031  2277  2455   3020   3664
  Mistake         193  1537  2919  4210  5500  13076  37487
2 Vote            1.0   0.4   0.3   0.3   0.3    0.3    0.3
  Avg. (unnorm)   1.0   0.4   0.4   0.3   0.3    0.3    0.3
  Avg. (norm)     1.0   0.4   0.4   0.3   0.3    0.3    0.3
  Last (unnorm)   1.0   1.3   0.6   0.6   0.6    0.3    0.3
  Last (norm)     1.0   1.3   0.6   0.6   0.6    0.3    0.3
  Rand. (unnorm)  1.0   0.4   0.3   0.3   0.3    0.3    0.3
  Rand. (norm)    1.0   0.4   0.3   0.3   0.3    0.3    0.3
  SupVec          124   653   840   946  1011   1184   1269
  Mistake         124   653   978  1228  1404   1986   2373
3 Vote            0.9   0.4   0.3   0.3   0.3    0.2    0.2
  Avg. (unnorm)   0.9   0.4   0.3   0.3   0.3    0.3    0.3
  Avg. (norm)     0.9   0.4   0.3   0.3   0.3    0.3    0.3
  Last (unnorm)   1.3   0.7   0.4   0.4   0.3    0.3    0.2
  Last (norm)     1.3   0.7   0.4   0.4   0.3    0.3    0.2
  Rand. (unnorm)  0.9   0.4   0.3   0.3   0.3    0.2    0.2
  Rand. (norm)    0.9   0.4   0.3   0.3   0.3    0.2    0.2
  SupVec          113   556   690   743   791    881    886
  Mistake         113   556   766   864   949   1127   1140

=================== DIGIT 6: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0  2.0  3.0  4.0  10.0 30.0
d Method
4 Vote            1.1  0.4  0.4  0.3  0.3  0.3  0.3
  Avg. (unnorm)   1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Avg. (norm)     1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Last (unnorm)   1.3  0.5  0.6  0.4  0.4  0.3  0.3
  Last (norm)     1.3  0.5  0.6  0.4  0.4  0.3  0.3
  Rand. (unnorm)  1.1  0.4  0.4  0.3  0.3  0.3  0.3
  Rand. (norm)    1.1  0.4  0.4  0.3  0.3  0.3  0.3
  SupVec          122  509  639  694  726  795  799
  Mistake         122  509  682  770  822  951  959
5 Vote            1.1  0.3  0.3  0.3  0.3  0.3  0.3
  Avg. (unnorm)   1.1  0.3  0.3  0.3  0.3  0.3  0.3
  Avg. (norm)     1.1  0.3  0.3  0.3  0.3  0.3  0.3
  Last (unnorm)   1.4  0.7  0.3  0.3  0.3  0.3  0.3
  Last (norm)     1.4  0.7  0.3  0.3  0.3  0.3  0.3
  Rand. (unnorm)  1.1  0.3  0.3  0.3  0.3  0.3  0.3
  Rand. (norm)    1.1  0.3  0.3  0.3  0.3  0.3  0.3
  SupVec          118  560  676  699  709  727  727
  Mistake         118  560  715  757  771  799  799
6 Vote            1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Avg. (unnorm)   1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Avg. (norm)     1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Last (unnorm)   0.9  0.7  0.3  0.3  0.3  0.3  0.3
  Last (norm)     0.9  0.7  0.3  0.3  0.3  0.3  0.3
  Rand. (unnorm)  1.0  0.4  0.3  0.3  0.3  0.3  0.3
  Rand. (norm)    1.0  0.4  0.3  0.3  0.3  0.3  0.3
  SupVec          135  552  652  680  680  685  685
  Mistake         135  552  685  731  734  743  743

============================================================
 STARTING EXPERIMENT FOR DIGIT: 7
============================================================

[7 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 222    | Test Error: 1.90%  (0.1s)
  T=1    | Mistakes: 1732   | Test Error: 1.51%  (0.7s)
  T=2    | Mistakes: 3264   | Test Error: 1.47%  (1.4s)
  T=3    | Mistakes: 4769   | Test Error: 1.47%  (2.1s)
  T=4    | Mistakes: 6297   | Test Error: 1.49%  (2.6s)
  T=10   | Mistakes: 15035  | Test Error: 1.50%  (6.6s)
  T=30   | Mistakes: 43464  | Test Error: 1.50%  (19.7s)

[7 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 167    | Test Error: 1.36%  (1.0s)
  T=1    | Mistakes: 927    | Test Error: 0.81%  (11.2s)
  T=2    | Mistakes: 1378   | Test Error: 0.65%  (26.1s)
  T=3    | Mistakes: 1748   | Test Error: 0.67%  (51.1s)
  T=4    | Mistakes: 2049   | Test Error: 0.67%  (78.1s)
  T=10   | Mistakes: 2997   | Test Error: 0.60%  (233.3s)
  T=30   | Mistakes: 3749   | Test Error: 0.57%  (767.7s)

[7 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 161    | Test Error: 1.26%  (0.8s)
  T=1    | Mistakes: 788    | Test Error: 0.57%  (11.7s)
  T=2    | Mistakes: 1095   | Test Error: 0.52%  (27.1s)
  T=3    | Mistakes: 1288   | Test Error: 0.50%  (43.6s)
  T=4    | Mistakes: 1411   | Test Error: 0.50%  (73.8s)
  T=10   | Mistakes: 1718   | Test Error: 0.47%  (187.5s)
  T=30   | Mistakes: 1808   | Test Error: 0.53%  (642.1s)

[7 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 170    | Test Error: 1.21%  (0.8s)
  T=1    | Mistakes: 762    | Test Error: 0.56%  (11.8s)
  T=2    | Mistakes: 1009   | Test Error: 0.47%  (26.8s)
  T=3    | Mistakes: 1161   | Test Error: 0.44%  (46.1s)
  T=4    | Mistakes: 1240   | Test Error: 0.46%  (70.6s)
  T=10   | Mistakes: 1372   | Test Error: 0.45%  (162.1s)
  T=30   | Mistakes: 1376   | Test Error: 0.47%  (586.6s)

[7 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 165    | Test Error: 1.45%  (0.9s)
  T=1    | Mistakes: 741    | Test Error: 0.57%  (11.6s)
  T=2    | Mistakes: 977    | Test Error: 0.54%  (26.6s)
  T=3    | Mistakes: 1107   | Test Error: 0.46%  (42.5s)
  T=4    | Mistakes: 1189   | Test Error: 0.46%  (62.7s)
  T=10   | Mistakes: 1264   | Test Error: 0.42%  (172.5s)
  T=30   | Mistakes: 1264   | Test Error: 0.41%  (548.2s)

[7 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 191    | Test Error: 1.47%  (0.9s)
  T=1    | Mistakes: 741    | Test Error: 0.59%  (12.9s)
  T=2    | Mistakes: 960    | Test Error: 0.52%  (29.5s)
  T=3    | Mistakes: 1078   | Test Error: 0.47%  (47.1s)
  T=4    | Mistakes: 1139   | Test Error: 0.45%  (58.8s)
  T=10   | Mistakes: 1277   | Test Error: 0.40%  (183.6s)
  T=30   | Mistakes: 1277   | Test Error: 0.43%  (541.4s)

=================== DIGIT 7: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0   2.0   3.0   4.0    10.0   30.0
d Method
1 Vote            1.9   1.5   1.5   1.5   1.5    1.5    1.5
  Avg. (unnorm)   1.9   1.5   1.5   1.5   1.5    1.5    1.5
  Avg. (norm)     2.0   1.5   1.5   1.5   1.4    1.5    1.5
  Last (unnorm)   2.3   2.3   2.4   2.7   2.3    2.2    1.9
  Last (norm)     2.3   2.3   2.4   2.7   2.3    2.2    1.9
  Rand. (unnorm)  1.9   1.5   1.5   1.5   1.5    1.5    1.5
  Rand. (norm)    1.9   1.5   1.5   1.5   1.5    1.5    1.5
  SupVec          222  1732  2260  2569  2810   3493   4279
  Mistake         222  1732  3264  4769  6297  15035  43464
2 Vote            1.4   0.8   0.6   0.7   0.7    0.6    0.6
  Avg. (unnorm)   1.3   0.8   0.7   0.7   0.7    0.6    0.6
  Avg. (norm)     1.3   0.8   0.7   0.7   0.7    0.6    0.6
  Last (unnorm)   1.5   0.9   0.8   0.8   0.7    0.8    0.5
  Last (norm)     1.5   0.9   0.8   0.8   0.7    0.8    0.5
  Rand. (unnorm)  1.4   0.8   0.6   0.7   0.7    0.6    0.6
  Rand. (norm)    1.4   0.8   0.6   0.7   0.7    0.6    0.6
  SupVec          167   927  1157  1315  1421   1675   1827
  Mistake         167   927  1378  1748  2049   2997   3749
3 Vote            1.3   0.6   0.5   0.5   0.5    0.5    0.5
  Avg. (unnorm)   1.2   0.5   0.5   0.5   0.5    0.5    0.5
  Avg. (norm)     1.2   0.5   0.5   0.5   0.5    0.5    0.5
  Last (unnorm)   1.5   0.8   0.7   0.5   0.6    0.5    0.5
  Last (norm)     1.5   0.8   0.7   0.5   0.6    0.5    0.5
  Rand. (unnorm)  1.3   0.6   0.5   0.5   0.5    0.5    0.5
  Rand. (norm)    1.3   0.6   0.5   0.5   0.5    0.5    0.5
  SupVec          161   788   980  1084  1155   1297   1324
  Mistake         161   788  1095  1288  1411   1718   1808

=================== DIGIT 7: TABLE 2 (d=4, 5, 6) ===================

                 0.1  1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            1.2  0.6   0.5   0.4   0.5   0.4   0.5
  Avg. (unnorm)   1.2  0.6   0.5   0.4   0.5   0.4   0.4
  Avg. (norm)     1.2  0.6   0.5   0.4   0.5   0.4   0.4
  Last (unnorm)   1.6  0.6   0.6   0.7   0.5   0.5   0.5
  Last (norm)     1.6  0.6   0.6   0.7   0.5   0.5   0.5
  Rand. (unnorm)  1.2  0.6   0.5   0.4   0.5   0.4   0.5
  Rand. (norm)    1.2  0.6   0.5   0.4   0.5   0.4   0.5
  SupVec          170  762   931  1024  1069  1135  1137
  Mistake         170  762  1009  1161  1240  1372  1376
5 Vote            1.4  0.6   0.5   0.5   0.5   0.4   0.4
  Avg. (unnorm)   1.4  0.6   0.5   0.5   0.5   0.4   0.4
  Avg. (norm)     1.4  0.6   0.5   0.5   0.5   0.4   0.4
  Last (unnorm)   1.5  0.7   0.7   0.4   0.5   0.4   0.4
  Last (norm)     1.5  0.7   0.7   0.4   0.5   0.4   0.4
  Rand. (unnorm)  1.4  0.6   0.5   0.5   0.5   0.4   0.4
  Rand. (norm)    1.4  0.6   0.5   0.5   0.5   0.4   0.4
  SupVec          165  741   909   996  1049  1078  1078
  Mistake         165  741   977  1107  1189  1264  1264
6 Vote            1.5  0.6   0.5   0.5   0.4   0.4   0.4
  Avg. (unnorm)   1.4  0.6   0.5   0.5   0.4   0.4   0.4
  Avg. (norm)     1.4  0.6   0.5   0.5   0.4   0.4   0.4
  Last (unnorm)   1.5  0.9   0.5   0.5   0.4   0.4   0.4
  Last (norm)     1.5  0.9   0.5   0.5   0.4   0.4   0.4
  Rand. (unnorm)  1.5  0.6   0.5   0.5   0.4   0.4   0.4
  Rand. (norm)    1.5  0.6   0.5   0.5   0.4   0.4   0.4
  SupVec          191  741   905   978  1012  1101  1101
  Mistake         191  741   960  1078  1139  1277  1277

============================================================
 STARTING EXPERIMENT FOR DIGIT: 8
============================================================

[8 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 542    | Test Error: 5.87%  (0.2s)
  T=1    | Mistakes: 5402   | Test Error: 5.22%  (1.7s)
  T=2    | Mistakes: 10517  | Test Error: 5.15%  (3.3s)
  T=3    | Mistakes: 15530  | Test Error: 5.09%  (4.9s)
  T=4    | Mistakes: 20617  | Test Error: 5.08%  (6.5s)
  T=10   | Mistakes: 50669  | Test Error: 5.17%  (16.5s)
  T=30   | Mistakes: 149928 | Test Error: 5.13%  (145.2s)

[8 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 307    | Test Error: 2.68%  (2.1s)
  T=1    | Mistakes: 1562   | Test Error: 1.22%  (15.5s)
  T=2    | Mistakes: 2329   | Test Error: 1.13%  (33.3s)
  T=3    | Mistakes: 2911   | Test Error: 1.06%  (57.5s)
  T=4    | Mistakes: 3401   | Test Error: 1.01%  (100.7s)
  T=10   | Mistakes: 5121   | Test Error: 0.92%  (268.9s)
  T=30   | Mistakes: 7004   | Test Error: 0.93%  (931.9s)

[8 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 272    | Test Error: 2.37%  (1.0s)
  T=1    | Mistakes: 1226   | Test Error: 1.05%  (15.6s)
  T=2    | Mistakes: 1732   | Test Error: 0.92%  (34.6s)
  T=3    | Mistakes: 2054   | Test Error: 0.85%  (52.5s)
  T=4    | Mistakes: 2287   | Test Error: 0.81%  (82.2s)
  T=10   | Mistakes: 2839   | Test Error: 0.81%  (237.8s)
  T=30   | Mistakes: 3034   | Test Error: 0.78%  (818.0s)

[8 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 256    | Test Error: 2.33%  (1.0s)
  T=1    | Mistakes: 1167   | Test Error: 0.98%  (12.8s)
  T=2    | Mistakes: 1539   | Test Error: 0.86%  (30.0s)
  T=3    | Mistakes: 1744   | Test Error: 0.86%  (49.1s)
  T=4    | Mistakes: 1892   | Test Error: 0.80%  (75.5s)
  T=10   | Mistakes: 2215   | Test Error: 0.71%  (215.6s)
  T=30   | Mistakes: 2232   | Test Error: 0.73%  (697.3s)

[8 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 239    | Test Error: 2.30%  (1.0s)
  T=1    | Mistakes: 1117   | Test Error: 0.93%  (15.0s)
  T=2    | Mistakes: 1489   | Test Error: 0.86%  (34.9s)
  T=3    | Mistakes: 1666   | Test Error: 0.73%  (55.8s)
  T=4    | Mistakes: 1798   | Test Error: 0.74%  (70.7s)
  T=10   | Mistakes: 1930   | Test Error: 0.74%  (220.5s)
  T=30   | Mistakes: 1938   | Test Error: 0.81%  (647.8s)

[8 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 262    | Test Error: 2.67%  (1.1s)
  T=1    | Mistakes: 1245   | Test Error: 1.10%  (15.7s)
  T=2    | Mistakes: 1625   | Test Error: 0.90%  (33.3s)
  T=3    | Mistakes: 1828   | Test Error: 0.84%  (52.5s)
  T=4    | Mistakes: 1895   | Test Error: 0.82%  (81.9s)
  T=10   | Mistakes: 2007   | Test Error: 0.80%  (210.2s)
  T=30   | Mistakes: 2010   | Test Error: 0.77%  (623.3s)

=================== DIGIT 8: TABLE 1 (d=1, 2, 3) ===================

                 0.1   1.0    2.0    3.0    4.0    10.0    30.0
d Method
1 Vote            5.9   5.2    5.1    5.1    5.1    5.2     5.1
  Avg. (unnorm)   5.8   5.2    5.1    5.1    5.1    5.2     5.1
  Avg. (norm)     6.0   5.2    5.1    5.1    5.1    5.1     5.1
  Last (unnorm)   9.5  13.7    8.6    8.1    8.1    9.7     6.7
  Last (norm)     9.5  13.7    8.6    8.1    8.1    9.7     6.7
  Rand. (unnorm)  5.9   5.2    5.1    5.1    5.1    5.2     5.1
  Rand. (norm)    5.9   5.2    5.1    5.1    5.1    5.2     5.1
  SupVec          542  5402   6963   7819   8377  10244   12278
  Mistake         542  5402  10517  15530  20617  50669  149928
2 Vote            2.7   1.2    1.1    1.1    1.0    0.9     0.9
  Avg. (unnorm)   2.7   1.2    1.1    1.1    1.0    0.9     0.9
  Avg. (norm)     2.7   1.2    1.1    1.1    1.0    0.9     0.9
  Last (unnorm)   4.0   1.5    1.4    1.3    1.1    1.2     0.9
  Last (norm)     4.0   1.5    1.4    1.3    1.1    1.2     0.9
  Rand. (unnorm)  2.7   1.2    1.1    1.1    1.0    0.9     0.9
  Rand. (norm)    2.7   1.2    1.1    1.1    1.0    0.9     0.9
  SupVec          307  1562   1947   2170   2308   2754    3074
  Mistake         307  1562   2329   2911   3401   5121    7004
3 Vote            2.4   1.0    0.9    0.8    0.8    0.8     0.8
  Avg. (unnorm)   2.2   1.1    0.9    0.8    0.8    0.8     0.8
  Avg. (norm)     2.2   1.1    0.9    0.8    0.8    0.8     0.8
  Last (unnorm)   3.4   1.5    1.1    1.1    0.9    0.7     0.8
  Last (norm)     3.4   1.5    1.1    1.1    0.9    0.7     0.8
  Rand. (unnorm)  2.4   1.0    0.9    0.8    0.8    0.8     0.8
  Rand. (norm)    2.4   1.0    0.9    0.8    0.8    0.8     0.8
  SupVec          272  1226   1568   1748   1861   2090    2160
  Mistake         272  1226   1732   2054   2287   2839    3034

=================== DIGIT 8: TABLE 2 (d=4, 5, 6) ===================

                 0.1   1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            2.3   1.0   0.9   0.9   0.8   0.7   0.7
  Avg. (unnorm)   2.2   1.0   0.8   0.9   0.8   0.7   0.7
  Avg. (norm)     2.2   1.0   0.8   0.9   0.8   0.7   0.7
  Last (unnorm)   4.1   1.4   0.8   1.0   0.9   0.7   0.7
  Last (norm)     4.1   1.4   0.8   1.0   0.9   0.7   0.7
  Rand. (unnorm)  2.3   1.0   0.9   0.9   0.8   0.7   0.7
  Rand. (norm)    2.3   1.0   0.9   0.9   0.8   0.7   0.7
  SupVec          256  1167  1416  1538  1616  1799  1806
  Mistake         256  1167  1539  1744  1892  2215  2232
5 Vote            2.3   0.9   0.9   0.7   0.7   0.7   0.8
  Avg. (unnorm)   2.2   0.9   0.9   0.8   0.8   0.7   0.8
  Avg. (norm)     2.2   0.9   0.9   0.8   0.8   0.7   0.8
  Last (unnorm)   3.2   1.3   1.0   0.8   0.9   0.8   0.8
  Last (norm)     3.2   1.3   1.0   0.8   0.9   0.8   0.8
  Rand. (unnorm)  2.3   0.9   0.9   0.7   0.7   0.7   0.8
  Rand. (norm)    2.3   0.9   0.9   0.7   0.7   0.7   0.8
  SupVec          239  1117  1395  1520  1610  1675  1678
  Mistake         239  1117  1489  1666  1798  1930  1938
6 Vote            2.7   1.1   0.9   0.8   0.8   0.8   0.8
  Avg. (unnorm)   2.6   1.1   0.9   0.8   0.8   0.8   0.8
  Avg. (norm)     2.6   1.1   0.9   0.8   0.8   0.8   0.8
  Last (unnorm)   3.8   1.5   0.9   0.8   0.8   0.8   0.8
  Last (norm)     3.8   1.5   0.9   0.8   0.8   0.8   0.8
  Rand. (unnorm)  2.7   1.1   0.9   0.8   0.8   0.8   0.8
  Rand. (norm)    2.7   1.1   0.9   0.8   0.8   0.8   0.8
  SupVec          262  1245  1531  1656  1693  1748  1748
  Mistake         262  1245  1625  1828  1895  2007  2010

============================================================
 STARTING EXPERIMENT FOR DIGIT: 9
============================================================

[9 vs Rest] ======= Polynomial Degree d = 1 =======
  T=0.1  | Mistakes: 503    | Test Error: 4.62%  (0.2s)
  T=1    | Mistakes: 4065   | Test Error: 4.12%  (1.3s)
  T=2    | Mistakes: 7839   | Test Error: 4.00%  (2.6s)
  T=3    | Mistakes: 11576  | Test Error: 3.92%  (3.9s)
  T=4    | Mistakes: 15279  | Test Error: 3.93%  (5.2s)
  T=10   | Mistakes: 37245  | Test Error: 3.90%  (12.7s)
  T=30   | Mistakes: 109880 | Test Error: 3.90%  (59.0s)

[9 vs Rest] ======= Polynomial Degree d = 2 =======
  T=0.1  | Mistakes: 321    | Test Error: 2.55%  (2.1s)
  T=1    | Mistakes: 1622   | Test Error: 1.27%  (17.4s)
  T=2    | Mistakes: 2444   | Test Error: 1.03%  (41.8s)
  T=3    | Mistakes: 3080   | Test Error: 1.04%  (71.8s)
  T=4    | Mistakes: 3595   | Test Error: 0.96%  (81.9s)
  T=10   | Mistakes: 5600   | Test Error: 0.90%  (279.8s)
  T=30   | Mistakes: 7592   | Test Error: 0.90%  (974.5s)

[9 vs Rest] ======= Polynomial Degree d = 3 =======
  T=0.1  | Mistakes: 286    | Test Error: 2.05%  (1.1s)
  T=1    | Mistakes: 1319   | Test Error: 1.07%  (14.0s)
  T=2    | Mistakes: 1834   | Test Error: 0.85%  (31.1s)
  T=3    | Mistakes: 2144   | Test Error: 0.81%  (49.6s)
  T=4    | Mistakes: 2407   | Test Error: 0.75%  (65.1s)
  T=10   | Mistakes: 3085   | Test Error: 0.70%  (185.6s)
  T=30   | Mistakes: 3190   | Test Error: 0.70%  (809.8s)

[9 vs Rest] ======= Polynomial Degree d = 4 =======
  T=0.1  | Mistakes: 259    | Test Error: 2.08%  (0.9s)
  T=1    | Mistakes: 1169   | Test Error: 1.04%  (13.0s)
  T=2    | Mistakes: 1556   | Test Error: 0.78%  (35.2s)
  T=3    | Mistakes: 1769   | Test Error: 0.75%  (57.3s)
  T=4    | Mistakes: 1908   | Test Error: 0.74%  (75.9s)
  T=10   | Mistakes: 2311   | Test Error: 0.72%  (228.9s)
  T=30   | Mistakes: 2362   | Test Error: 0.73%  (694.2s)

[9 vs Rest] ======= Polynomial Degree d = 5 =======
  T=0.1  | Mistakes: 283    | Test Error: 2.29%  (1.0s)
  T=1    | Mistakes: 1173   | Test Error: 1.00%  (13.6s)
  T=2    | Mistakes: 1475   | Test Error: 0.85%  (32.8s)
  T=3    | Mistakes: 1662   | Test Error: 0.78%  (51.1s)
  T=4    | Mistakes: 1853   | Test Error: 0.76%  (90.7s)
  T=10   | Mistakes: 2060   | Test Error: 0.77%  (206.9s)
  T=30   | Mistakes: 2060   | Test Error: 0.80%  (685.2s)

[9 vs Rest] ======= Polynomial Degree d = 6 =======
  T=0.1  | Mistakes: 286    | Test Error: 2.41%  (1.1s)
  T=1    | Mistakes: 1172   | Test Error: 1.05%  (15.9s)
  T=2    | Mistakes: 1539   | Test Error: 0.88%  (39.5s)
  T=3    | Mistakes: 1804   | Test Error: 0.84%  (63.7s)
  T=4    | Mistakes: 1962   | Test Error: 0.78%  (69.8s)
  T=10   | Mistakes: 2055   | Test Error: 0.77%  (206.3s)
  T=30   | Mistakes: 2055   | Test Error: 0.78%  (682.5s)

=================== DIGIT 9: TABLE 1 (d=1, 2, 3) ===================

                  0.1   1.0   2.0    3.0    4.0    10.0    30.0
d Method
1 Vote             4.6   4.1   4.0    3.9    3.9    3.9     3.9
  Avg. (unnorm)    4.7   4.1   4.0    3.9    3.9    3.9     3.9
  Avg. (norm)      4.7   4.1   4.0    3.9    3.9    3.9     3.9
  Last (unnorm)   12.3   7.3   6.0    4.7    5.3    5.3     6.4
  Last (norm)     12.3   7.3   6.0    4.7    5.3    5.3     6.4
  Rand. (unnorm)   4.6   4.1   4.0    3.9    3.9    3.9     3.9
  Rand. (norm)     4.6   4.1   4.0    3.9    3.9    3.9     3.9
  SupVec           503  4065  5201   5822   6288   7671    9107
  Mistake          503  4065  7839  11576  15279  37245  109880
2 Vote             2.5   1.3   1.0    1.0    1.0    0.9     0.9
  Avg. (unnorm)    2.5   1.2   1.0    1.0    1.0    0.9     0.9
  Avg. (norm)      2.5   1.2   1.0    1.0    1.0    0.9     0.9
  Last (unnorm)    3.3   1.5   1.4    1.6    1.2    0.8     1.0
  Last (norm)      3.3   1.5   1.4    1.6    1.2    0.8     1.0
  Rand. (unnorm)   2.5   1.3   1.0    1.0    1.0    0.9     0.9
  Rand. (norm)     2.5   1.3   1.0    1.0    1.0    0.9     0.9
  SupVec           321  1622  2032   2269   2423   2863    3182
  Mistake          321  1622  2444   3080   3595   5600    7592
3 Vote             2.0   1.1   0.8    0.8    0.7    0.7     0.7
  Avg. (unnorm)    2.0   1.0   0.9    0.8    0.8    0.7     0.7
  Avg. (norm)      2.0   1.0   0.9    0.8    0.8    0.7     0.7
  Last (unnorm)    3.6   1.5   1.0    1.0    0.8    0.8     0.7
  Last (norm)      3.6   1.5   1.0    1.0    0.8    0.8     0.7
  Rand. (unnorm)   2.0   1.1   0.8    0.8    0.7    0.7     0.7
  Rand. (norm)     2.0   1.1   0.8    0.8    0.7    0.7     0.7
  SupVec           286  1319  1614   1771   1900   2190    2223
  Mistake          286  1319  1834   2144   2407   3085    3190

=================== DIGIT 9: TABLE 2 (d=4, 5, 6) ===================

                 0.1   1.0   2.0   3.0   4.0   10.0  30.0
d Method
4 Vote            2.1   1.0   0.8   0.7   0.7   0.7   0.7
  Avg. (unnorm)   2.0   1.0   0.8   0.7   0.7   0.7   0.7
  Avg. (norm)     2.0   1.0   0.8   0.7   0.7   0.7   0.7
  Last (unnorm)   2.9   1.8   1.0   0.8   0.8   0.8   0.7
  Last (norm)     2.9   1.8   1.0   0.8   0.8   0.8   0.7
  Rand. (unnorm)  2.1   1.0   0.8   0.7   0.7   0.7   0.7
  Rand. (norm)    2.1   1.0   0.8   0.7   0.7   0.7   0.7
  SupVec          259  1169  1424  1560  1635  1863  1885
  Mistake         259  1169  1556  1769  1908  2311  2362
5 Vote            2.3   1.0   0.8   0.8   0.8   0.8   0.8
  Avg. (unnorm)   2.3   0.9   0.9   0.8   0.7   0.7   0.8
  Avg. (norm)     2.3   0.9   0.9   0.8   0.7   0.7   0.8
  Last (unnorm)   2.8   1.2   0.9   0.7   0.9   0.8   0.8
  Last (norm)     2.8   1.2   0.9   0.7   0.9   0.8   0.8
  Rand. (unnorm)  2.3   1.0   0.8   0.8   0.8   0.8   0.8
  Rand. (norm)    2.3   1.0   0.8   0.8   0.8   0.8   0.8
  SupVec          283  1173  1401  1503  1622  1734  1734
  Mistake         283  1173  1475  1662  1853  2060  2060
6 Vote            2.4   1.0   0.9   0.8   0.8   0.8   0.8
  Avg. (unnorm)   2.5   1.0   0.9   0.8   0.8   0.8   0.8
  Avg. (norm)     2.5   1.0   0.9   0.8   0.8   0.8   0.8
  Last (unnorm)   3.0   1.3   1.2   0.8   0.8   0.8   0.8
  Last (norm)     3.0   1.3   1.2   0.8   0.8   0.8   0.8
  Rand. (unnorm)  2.4   1.0   0.9   0.8   0.8   0.8   0.8
  Rand. (norm)    2.4   1.0   0.9   0.8   0.8   0.8   0.8
  SupVec          286  1172  1462  1642  1725  1761  1761
  Mistake         286  1172  1539  1804  1962  2055  2055